[project]
name = "wellbeingcoach"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "fastapi>=0.136.1",
    "httpx>=0.28.1",
    "openai>=2.37.0",
    "pytest>=9.0.3",
    "slowapi>=0.1.9",
    "sse-starlette>=3.4.4",
    "uvicorn>=0.47.0",
]
